### ISSUE TITLE
SyntaxWarning, but can't find error

### ISSUE THREAD

**Issue by basic5253** [basic5253/Fourier-Series-Bot#1]
VS Code is saying the following SyntaxWarning, and I'm not sure what I'm doing wrong.

SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  ROWs = 1 (maxN-1) // COLs #rows in plt
Traceback (most recent call last):
  File "<where i stored my file>" , line 41, in <module>
    ROWs = 1 (maxN-1) // COLs #rows in plt
TypeError: 'int' object is not callable

**Comment by deusdevok** [comment]
Hi ! I can help you fixing this warnings and other possible bugs. Let me know if you still need help, I'll be available.

**Comment by basic5253** [comment]
Yes, please copy the repository and put in a pull request! Thanks!

**Comment by carlosbionic** [comment]
Apparently I don't have permissions to make pull requests?
